### ISSUE TITLE
Not backward compatible for 4.6 tree

### ISSUE THREAD

**Issue by PatelUtkarsh** [xwp/wp-customizer-browser-history#17]
Tested on a fresh install of 4.6.1 with `master` branch and it is throwing error.

Error: **Uncaught TypeError: Cannot read property 'get'** 
`changesetStatus = api.state( 'changesetStatus' ).get();` 
https://github.com/xwp/wp-customizer-browser-history/blob/ce6502bda7b7876b8e69ea01d033302aa2ec0c03/customizer-browser-history-controls.js#L134 

As changeset was introduced in 4.7.
This plugin should be backward compatible or we should change tag `Requires at least` to 4.7.

**Comment by westonruter** [comment]
@PatelUtkarsh you're right! How does #18 work for you?
