### ISSUE TITLE
Restore preview device size selection

### ISSUE THREAD

**Issue by frankiejarrett** [xwp/wp-customizer-browser-history#3]
Just came across a case where I was doing some testing inside the Customizer using the Tablet device size and refreshed my browser bringing me back to Desktop mode. Would be great to save a click and be brought back to the Customizer in the same way I left it.

**Comment by westonruter** [comment]
Oh, good call!

**Comment by westonruter** [comment]
@fjarrett give this a shot: https://github.com/xwp/wp-customizer-browser-history/pull/4
